config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "restaurants#homepage"
  get 'reviews/new'

  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :reviews, dependent: :destroy
    validates :name, presence: true
    validates :address, presence: true
    validates :phone_number, presence: true
    validates :category, presence: true
    validates :category, inclusion: { in: %w(chinese italian japanese french belgian) }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy ]

  # GET /restaurants
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: "Restaurant was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /restaurants/1
  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: "Restaurant was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /restaurants/1
  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: "Restaurant was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class RewiewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/rewiews_helper.rb
module RewiewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.submit %>
<% end %>

app/views/restaurants/_list.html.erb
<div id="restaurants">
  <% restaurants.each do |restaurant| %>
    <%= render restaurant %>
    <p>
      <%= link_to "Show this restaurant", restaurant %>
    </p>
  <% end %>
</div>

app/views/restaurants/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"     aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled">Disabled</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
   </nav>

app/views/restaurants/_restaurant.html.erb
<div id="<%= dom_id restaurant %>">
  <p>
    <strong>Name:</strong>
    <%= @restaurant.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @restaurant.address %>
  </p>

  <p>
    <strong>Stars:</strong>

  </p>

</div>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Show this restaurant", @restaurant %> |
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/restaurants/homepage.html.erb
<div id="banner">
   <h1>Choose where you want eat</h1>
  <div class="text-banner"><%= link_to "restaurantes", restaurants_path, class:"restaurant-btn" %></div>
</div>

<h1>Home Page</h1>

app/views/restaurants/index.html.erb
<h1>Mis Restaurantes</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <a href="<%= restaurant_path(restaurant) %>">
        <%= restaurant.name %>
      </a>
    </li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<p><%= @restaurant.address %></p>

<p style="color: green"><%= notice %></p>

<%= render @restaurant %>

<p><strong>Reviews</strong></p>
<ul class="list-group">
  <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item">
      <%= review.content %>
      <%= link_to "Delete",
        review_path(review),
        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
      %>
    </li>
  <% end %>
</ul>
<br>

<div>
  <%= link_to "Edit this restaurant", edit_restaurant_path(@restaurant) %> |
  <%= link_to "Back to restaurants", restaurants_path %>

  <%= button_to "Destroy this restaurant", @restaurant, method: :delete %>
</div>

app/views/rewiews/new.html.erb
<h1>New Review</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>